[package]
name = "starnamics/rongo"
description = "MongoDB communication module for ease of use"
version = "0.1.0"
license = "MIT"
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"
exclude = [
  "LICENSE", "README.md"
]
